export enum EPagesActions {
  SET_ACTIVE_PATH = "SET_ACTIVE_PATH"
}

export enum EMeteoActions {
  START_CURRENT_METEO_DATA_LOAD = "START_CURRENT_METEO_DATA_LOAD",
  SUCCESS_CURRENT_METEO_DATA_LOAD = "SUCCESS_CURRENT_METEO_DATA_LOAD",
  FAILURE_CURRENT_METEO_DATA_LOAD = "FAILURE_CURRENT_METEO_DATA_LOAD",

  START_FIVEDAY_METEO_DATA_LOAD = "START_FIVEDAY_METEO_DATA_LOAD",
  SUCCESS_FIVEDAY_METEO_DATA_LOAD = "SUCCESS_FIVEDAY_METEO_DATA_LOAD",
  FAILURE_FIVEDAY_METEO_DATA_LOAD = "FAILURE_FIVEDAY_METEO_DATA_LOAD",

  SET_COUNT_METEO_CELLS_ON_SCREEN = "SET_COUNT_METEO_CELLS_ON_SCREEN"
}
